
  name: hnterm
  version: '0.1'
  summary: Hacker News in the terminal
  description: |
    Interctive browsing of Hacker News in the terminal.

  base: core18
  grade: devel
  confinement: devmode

  parts:
    hnterm:
      source: https://github.com/ggerganov/hnterm
      source-type: git
      plugin: cmake
      build-packages:
        - g++
        - make
        - libncurses5-dev
        - libcurl4-openssl-dev
      stage-packages:
        - libncurses5
        - libcurl4

  apps:
    hnterm:
      command: bin/hnterm
